### ISSUE TITLE
PracticeParty#4

### ISSUE THREAD

**Issue by ebakazu** [tutorialmaker/PracticePy#101]
# [PracticeParty#4](https://playground-i.com/contents/87/)

## 主催者:ebakazu(開催日時:19:00~22:00)

[ebakazu](https://github.com/ebakazu)

## Agenda
毎週月曜日~ 19:00 ~
PracticePyのもくもく会
issueで設定している目標に沿って各自もくもく

会開始時 (19:00):目標の明示、次週代表者決定を行う。
代表者がGithubにIssueを立てる。コメント欄に目標を書く。
申し込み:GithubのIssue, Playground

**Comment by takuto0212** [comment]
## 目標（12/10まで）
day7まで終わらせる

**Comment by ebakazu** [comment]
day6を終わらせる
