### ISSUE TITLE
PracticeParty#5

### ISSUE THREAD

**Issue by YosukeHoshi** [tutorialmaker/PracticePy#110]
# [PracticeParty#5](https://playground-i.com/contents/93/)

## 主催者

[yosukehoshi](https://github.com/yosukehoshi)

## 要約

毎週月曜日~ 19:00 ~
PracticePyのもくもく会
issueで設定している目標に沿って各自もくもく

会開始時 (19:00):目標の明示、次週代表者決定を行う。
代表者がGithubにIssueを立てる。コメント欄に目標を書く。
申し込み:GithubのIssue, Playground

**Comment by ebakazu** [comment]
day7をやる

**Comment by takuto0212** [comment]
day8をやる

**Comment by YosukeHoshi** [comment]
day6をやる
